# Generated by Django 4.2.1 on 2023-06-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.endereco'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produtos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.produto'),
        ),
    ]
